solid/solid-client

.gitignore, package.json
Also saves a minified copy when doing `npm run build`
=> Add minify step to build script

lib/identity.js
=> Fix owl:seeAlso (change it to rdfs:seeAlso)

test/unit/vocab-test.js
=> Add Vocab test

package.json
=> Fix 'npm run build' to account for missing dist/ directory

lib/identity.js, lib/util/graph-util.js, lib/vocab.js, test/resources/profile-ldnode.js, test/unit/solid-profile-test.js
=> Fix graph append logic for loading profile

lib/identity.js, lib/util/graph-util.js, lib/vocab.js, test/resources/profile-ldnode.js, test/unit/solid-profile-test.js
Fixes issue #50.
(Btw, merge PR #54 first, before merging this one).
=> Make sure parsed extended profile links are a unique set

CHANGELOG.md, README.md, lib/identity.js, lib/solid/container.js, lib/solid/profile.js, lib/util/rdflib-ns.js, lib/vocab.js, lib/web.js, package.json, test/unit/solid-profile-test.js, test/unit/vocab-test.js
Implements #57.
Based on 'rdf-ns' package.
=> Switch to Namespace-based vocab

CHANGELOG.md, lib/identity.js, lib/normalize-profile.js, lib/solid/profile.js, test/unit/solid-profile-test.js
Also restrict `profile.preferences` to just one link.
Fixes issue #60.
=> Restrict profile to just one private and one public type index

lib/util/web-util.js, test/unit/web-util-test.js
=> Change web.patch() to use a single INSERT for all triples

CHANGELOG.md, README.md, demo/index.html, lib/solid/index-registration.js, lib/solid/profile.js, lib/type-registry.js, test/unit/type-registry-test.js
=> Implement profile.unregisterType()

CHANGELOG.md, README.md, lib/solid/container.js, lib/solid/index-registration.js, lib/solid/resource.js, lib/solid/response.js, lib/type-registry.js, lib/web.js, package.json
=> Implement web.createContainer()

CHANGELOG.md, README.md, lib/solid/response.js, lib/vocab.js
=> Add response.parsedGraph() convenience method

CHANGELOG.md, lib/solid/response.js
=> Expand isContainer to also count BasicContainer

lib/identity.js
Switched to `solid:account` instead of `foaf:account`.
=> Use solid:account

demo/index.html, lib/permissions.js
Authorization object encapsulates Agent + url + isDefaultForNew
Editing the documentation
=> Adding Authorization Object

lib/identity.js, lib/solid/response.js
Minor refactoring of comments & promise usage.
=> Refactor identity.discoverWebID()

CHANGELOG.md, README.md, lib/solid/profile.js, lib/vocab.js, test/resources/profile-ldnode.js, test/unit/solid-profile-test.js
=> Implement profile.name, .picture, .find() and .findAll()

index.js, lib/app-registry.js, lib/registry.js, lib/solid/profile.js, lib/type-registry.js, lib/util/web-util.js, test/integration/solid-profile-test.js, test/resources/app-registry-listed.js, test/resources/app-registry-unlisted.js, test/unit/app-registry-test.js, test/unit/solid-profile-test.js, test/unit/type-registry-test.js
=> Implement initAppRegistryPrivate() & Public()

docs/installing.md
=> Further document webpack configuration

CHANGELOG.md, README.md, index.js, lib/app-registry.js, lib/solid/app-registration.js, lib/solid/profile.js, lib/vocab.js, test/integration/solid-profile-test.js, test/resources/app-registry-listed.js, test/unit/app-registry-test.js
Implements issue #109 and the epic https://github.com/solid/solid/issues/109.
=> Implement 'register app' functionality

package.json
=> Update solid-permissions to 0.2.1

package.json, src/identity.js, test/unit/identity-test.js
=> Full WebId support (including HTTP 303 based)

package.json, src/app-registry.js, src/type-registry.js, src/util/graph-util.js, test/resources/profile-extended.js, test/unit/app-registry-test.js, test/unit/type-registry-test.js
@dmitrizagidulin please review this
=> Really update the profile promised by addToTypeIndex

src/type-registry.js, test/unit/type-registry-test.js
Addresses #142.
@dmitrizagidulin plz review
=> Make loadTypeRegistry handle no registries loading

package.json
@dmitrizagidulin FYI - I'll merge once tests pass
=> Add forgotten babel-loader, move babel to devDependencies

package.json
=> Update solid-web-client to 0.2.0

src/registry.js
=> Make isListed / isUnlisted query more specific

README.md
Quite a good joke, right after *recursively*, but not neccessarily needed here.
=> upd README : remove double word
